feature/topnav
Jalal999/training-renome pull request #1
Opened 2021-11-25 09:25 UTC by Jalal999

2021-11-25 10:03 UTC, VSlobolinskyi commented on .idea/vcs.xml
> +<?xml version="1.0" encoding="UTF-8"?>
I suggest you move away from intellij idea to VScode. In some projects we will be required to use some VScode extensions

2021-11-25 10:03 UTC, VSlobolinskyi commented on package.json
>      "react-scripts": "4.0.3",
Try edjecting react-scripts to see what's inside.

2021-11-25 10:03 UTC, VSlobolinskyi commented on src/components/navbar/navbar.scss
> +      transition: var(--transition);
Is there a need to have transition on the child as well?

2021-11-25 10:03 UTC, VSlobolinskyi commented on src/App.css
> +    --fixed-width: 620px;
If you decided to make a variable for something then be more specific with the variable name. For example "transition" doesn't carry a lot of meaning, instead I would name it something like "classic-linear". Same with colors instead of "primary-1" name it "dark-red", if you struggle with color names try this: chir.ag/projects/name-that-color/

2021-11-25 10:26 UTC, YuraLeo94 requested changes

2021-11-25 10:26 UTC, YuraLeo94 commented on src/components/navbar/navbar.scss
> +        }
Looks like you don't need this at this moment. Please remove

2021-11-25 10:26 UTC, YuraLeo94 commented on src/components/navbar/navbar.scss
> +  &__header{
`&__header{` please be consistent with space between _class name_ and _brace_ `&__header {`
Below you have the same issues fix them please.

2021-11-25 10:26 UTC, YuraLeo94 commented on src/App.css
> +}
For what purpose are you using this?

2021-11-25 10:26 UTC, YuraLeo94 commented on src/App.css
> +body {
Need to add space between line 29 and 30

2021-11-25 10:26 UTC, YuraLeo94 commented on src/App.js
> +// import logo from './logo.svg';
Looks like you forget to remove it

2021-11-25 10:26 UTC, YuraLeo94 commented on src/App.css
>  }
Where do you use it?

2021-11-25 10:58 UTC, Jose-Hash-Dev requested changes

2021-11-25 10:58 UTC, Jose-Hash-Dev commented on src/App.js
>  import './App.css';
Please use .scss file

2021-11-25 10:58 UTC, Jose-Hash-Dev commented on src/components/navbar/navbar.js
> +import React, { useState } from 'react';
Please use prettier

2021-11-25 10:58 UTC, Jose-Hash-Dev commented on src/components/navbar/navbar.js
> +                <div className={`${showCart ? 'nav__center__cart__container' : 'nav__center__cart__container nav__center__cart__container--show'}`}>
Why not only `nav__center__cart__container--show`?

2021-11-25 19:09 UTC, Jose-Hash-Dev requested changes

2021-11-25 19:09 UTC, Jose-Hash-Dev commented on src/components/navbar/navbar.js
> +        <nav>
`<nav>` is not necessary to use. You have already wrapped everything with `<div className='nav__center'>`

2021-11-26 13:42 UTC, YuraLeo94 requested changes

2021-11-26 13:42 UTC, YuraLeo94 commented on src/App.scss
> +    --clrBlack1: hsl(207, 73%, 3%);
`--clr-black-pearl` 
converter https://htmlcolors.com/color-converter
this link will help get more name for color https://chir.ag/projects/name-that-color/#02080D

2021-11-26 13:42 UTC, YuraLeo94 commented on src/App.scss
> +    --clrBlack2: hsl(210, 61%, 3%);
`--clrBlack2` same it's not best name
converter https://htmlcolors.com/hsl-to-hex
`clr-firefly` - https://chir.ag/projects/name-that-color/#03080C

2021-11-26 13:42 UTC, YuraLeo94 commented on src/App.scss
>  }
What's the big reason why you need to assign this to all elements?

2021-11-26 13:42 UTC, YuraLeo94 commented on src/components/navbar/navbar.scss
>        &__toggle:hover{
space between

2021-11-26 13:42 UTC, YuraLeo94 commented on src/components/navbar/buttons/navCart.scss
> +    &__ul a{
space between `&__ul a{` -> `&__ul a {`

2021-11-26 13:42 UTC, YuraLeo94 commented on src/components/navbar/buttons/navCart.scss
> +    &__ul a:hover{
space between

2021-11-26 13:42 UTC, YuraLeo94 commented on src/components/navbar/buttons/hamburger.scss
> +    &__ul a{
space between

2021-11-26 13:42 UTC, YuraLeo94 commented on src/components/navbar/buttons/hamburger.scss
> +    &__ul a:hover{
space between

2021-11-26 14:37 UTC, YuraLeo94 approved these changes

2021-11-26 15:06 UTC, Jose-Hash-Dev approved these changes

2021-11-26 15:32 UTC, VSlobolinskyi approved these changes

2021-11-30 12:16 UTC, merged